### ISSUE TITLE
Not working to convert the system AD date in laravel application

### ISSUE THREAD

**Issue by reysagar** [pratiksh404/nepalidate#10]
Hey,

I was trying to implement your nepalidate package into my laravel application, It working fine using the carbon now function with all formats but it's not working to convert the existing date and show the nepalidate output as you created the functions in the helper.php file.

I can't find the exact function to convert the ad date into bs using your package, I just want to know if It is possible, or the package only supports carbon:now functions.

**Comment by pratiksh404** [comment]
package supports as long as it is carbon instance

**Comment by reysagar** [comment]
I'm a little bit confused,

Do I need to create a separate public function for the date that I want to convert, I want to convert my invoice date which is default, It's in AD format in the system.

I can't see any other functions which is implemented on the controller file accept Carbon::now

```
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class NepaliDateController extends Controller
{
    public function index()
    {
        $now = Carbon::now();
        $nepaliDate = nepaliDate($now);
        return view('nepali-date', compact('nepaliDate'));
    }


}
```
Can I convert this below date into a BS format using your package, is it possible to do that?

`<b>{{$receipt_details->date_label}}</b> {{$receipt_details->invoice_date}}`

**Comment by reysagar** [comment]
Can you please tell me how can I implement it, I tried adding on the controller but didn't work,

example >>

```
public function convertToBsFormat($invoiceDate)
{
    // Convert the AD date to BS
    $bsDate = NepaliDate::parse($invoiceDate);

    // Format the BS date
    $bsFormattedDate = $bsDate->format('Y-m-d');

    return $bsFormattedDate;
}
```
The code present to call the invoice date and get the output is
`<b>{{$receipt_details->date_label}}</b> {{$receipt_details->invoice_date}}`

After creating the controller, trying to get BSDate output in the blade.php file like this by modifying the system default code
```
<!-- Assuming $receipt_details contains the receipt details object -->
@php
    $invoiceAdDate = $receipt_details->invoice_date;
    $invoiceBsDate = $this->convertToBsFormat($invoiceAdDate);
@endphp

<b>{{ $receipt_details->date_label }}</b> {{ $invoiceBsDate }}
```

**Comment by pratiksh404** [comment]
public function convertToBsFormat($invoiceDate)
{
    // Convert the AD date to BS
    $bsDate = NepaliDate::parse($invoiceDate);

    // Format the BS date
    $bsFormattedDate = toDetailBS(\Carbon\Carbon::create($invoiceDate));

    return $bsFormattedDate->year . '-'  .  $bsFormattedDate->month . '-' .  $bsFormattedDate->day;
}

**Comment by reysagar** [comment]
I modified the blade.php code like this,

`<b>{{ $receipt_details->date_label }}</b> {{ toDetailBS($receipt_details->invoice_date) }}`

but its not working, is this a correct code to execute in bs format using the controller that you just provided?

**Comment by pratiksh404** [comment]
You dont need to modify your code
```
<!-- Assuming $receipt_details contains the receipt details object -->
@php
    $invoiceAdDate = $receipt_details->invoice_date;
    $invoiceBsDate = $this->convertToBsFormat($invoiceAdDate);
@endphp

<b>{{ $receipt_details->date_label }}</b> {{ $invoiceBsDate }}
```

**Comment by reysagar** [comment]
Do I have to mention something on the helpers.php file? 
I have no idea just asking.

**Comment by pratiksh404** [comment]
Did you change `convertToBsFormat` function as below?

```
public function convertToBsFormat($invoiceDate)
{
    $bsFormattedDate = toDetailBS(\Carbon\Carbon::create($invoiceDate));

    return $bsFormattedDate->year . '-'  .  $bsFormattedDate->month . '-' .  $bsFormattedDate->day;
}

```

**Comment by reysagar** [comment]
Yes, I did along with the previous code available in the controller,

```
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class NepaliDateController extends Controller
{
    public function index()
    {
        $now = Carbon::now();
        $nepaliDate = nepaliDate($now);
        return view('nepali-date', compact('nepaliDate'));
    }


    public function convertToBsFormat($invoiceDate)
    {
    $bsFormattedDate = toDetailBS(\Carbon\Carbon::create($invoiceDate));

    return $bsFormattedDate->year . '-'  .  $bsFormattedDate->month . '-' .  $bsFormattedDate->day;
    }


}
```

**Comment by pratiksh404** [comment]
On your controller
```
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

class NepaliDateController extends Controller
{
    public function index()
    {
         $now = Carbon::now();
         $bsFormattedDate = toDetailBS(\Carbon\Carbon::create($invoiceDate));

        $nepaliDate = $bsFormattedDate->year . '-'  .  $bsFormattedDate->month . '-' .  $bsFormattedDate->day;
        return view('nepali-date', compact('nepaliDate'));
    }
}
```

On your view

`{{$nepaliDate }}`

**Comment by reysagar** [comment]
Output is blank when I use the below variable,

`{{$nepaliDate }}
`

**Comment by reysagar** [comment]
Sad to say that, still not working.

I tired a bunch of different approaches to modifying the controller but no change getting the blank output.

**Comment by reysagar** [comment]
Sad to say that, still not working.

I tired a bunch of different approaches to modifying the controller but no change getting the blank output.

**Comment by pratiksh404** [comment]
If you place the code mentioned on the controller in tinker it works

**Comment by reysagar** [comment]
I am trying to print the invoice in a pdf format, is that an issue?

**Comment by reysagar** [comment]
Is there any other way to call the function rather than the controller? might be my controller file is not working properly to get input values.

**Comment by reysagar** [comment]
![Xnip2023-05-16_22-18-53](https://github.com/pratiksh404/nepalidate/assets/125549844/9d36552a-2241-49a0-8835-1c8bac482f9a)

Carbon now is working perfectly fine you can see in the attachment, I want to convert the existing ad date into bs format whenever the system generates the invoice.

**Comment by reysagar** [comment]
I resolved it using parse, there is no need to create a controller file,
Here is the correct view file >>>

`({{nepaliDate(\Carbon\Carbon::parse($receipt_details->invoice_date))}})`

Thank you for your guidance.

**Comment by reysagar** [comment]
Here is my corrected helpers.php to do the conversion,

```
<?php

use Pratiksh\NepaliDate\NepaliDate;

if (!function_exists('toNepaliDate')) {
    function toNepaliDate($date, $format = 'l j F Y')
    {
        // Convert the date to a Carbon instance
        $carbonDate = \Carbon\Carbon::parse($date);
        
        // Convert the date to the Nepali calendar system
        $nepaliDate = NepaliDate::toBs($carbonDate);
        
        $default_ad_date = $default_datetime->format('Y-m-d H:i:s');

        // Convert the default transaction date from AD to BS format
        $default_bs_date = NepaliDate::createFromAdDate($default_ad_date)->getFormattedDate();
        
        // Format the Nepali date using the given format
        return $nepaliDate->formatLocalized($format);
    }
}
```
